install:
	install unison-inotify-process /usr/bin/unison-inotify-process
	unison-inotify-signal /usr/bin/unison-listen-start
	unison-listen-start /usr/bin/unison-listen-start
	unison-listen-startall /usr/bin/unison-listen-startall
	unison-listen-status /usr/bin/unison-listen-status
	unison-listen-stop /usr/bin/unison-listen-stop
	unison-listen-stopall /usr/bin/unison-listen-stop
	unison-syncall /usr/bin/unison-syncall
	unison-wakeall /usr/bin/unison-wakeall
