#!/bin/bash

PROFILE="$1"

LOCKFILE="/tmp/unison-inotify-$USER/$PROFILE.lock"
if [ ! -e "$LOCKFILE" ]; then
	echo "$LOCKFILE does not exist. Aborting." >&2
	exit 1
fi

echo "Stop listening to $PROFILE"
PID=`cat "$LOCKFILE"`
if [[ $PID -eq 0 ]]; then
	echo "Invalid PID: $PID"
	exit
fi
kill $PID
